import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="absolute w-full z-10">
          <div className='flex justify-between container text-white mx-auto p-8'>
            <Link className="font-bold text-3xl" href='/'>Home</Link>
            <div className='flex gap-4 text-xl'>
              <Link href='/dashboard'>Dashboard</Link>
              <Link href='/dashboard/about'>about</Link>
              <Link href='/dashboard/settings'>settings</Link>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
